import { type AppProps} from "next/app";

import { api } from "~/utils/api";

import "~/styles/globals.css";
import { SessionProvider } from "next-auth/react";
import { type Session } from "next-auth";
import Head from "next/head";
import { NextUIProvider } from "@nextui-org/react";
import NavBar from "~/components/nextui/Navbar";


const MyApp = ({ Component, pageProps }:AppProps<{
  session: Session;
}>) => {
  return (
    <NextUIProvider>
      <SessionProvider session={pageProps.session}>
        <Head>
          <title>Create T3 App</title>
          <meta name="description" content="Generated by create-t3-app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <NavBar />
        <Component {...pageProps} />
      </SessionProvider>
    </NextUIProvider>
  );
};

export default api.withTRPC(MyApp);
